### PR TITLE
Huge tree

### PR DESCRIPTION
**Pull request by grapesmoker**
Short description explaining the high-level reason for the pull request

## Changes

The `import_xml` command now constructs a parser with the `huge_tree=True` argument in order to be able to load large files such as those that come from Reg Z. This addresses issue #37.

Also, `timeline.html` is changed to display the correct timeline in landing mode.

## Testing

Try loading a regulation instance from Reg Z; it should succeed without reporting that the tree is too large.

## Review

- @chosak 

[Preview this PR without the whitespace changes](?w=0)

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Review by chosak — CHANGES_REQUESTED** [review]
If I run this against the example in #37:

```sh
$ ./manage.py import_xml ../regulations-xml/regulation/1026/2016-14782_20170101.xml
```

it fails with a 

```
django.db.utils.DataError: (1406, "Data too long for column 'marker' at row 47")
```

I note that the `marker` field [has a max length of 25 characters](https://github.com/cfpb/eregs-2.0/blob/master/eregs_core/models.py#L185), and there are some markers in the above-mentioned RegML file that exceed that, for example `marker="(ii1026-38-c-11026-38-c-1)"`

**Comment by grapesmoker** [comment]
Ok, wow, I had never seen markers like that. That's actually a mistake, which I will now investigate. Markers should never have such a form, which leads me to think something went wrong there.

**Review by chosak — APPROVED** [review]
Okay, if that's an error with the source file it shouldn't hold up this PR (as long as 25 characters is the correct limit). I can confirm that this change gets passed the reading step, and that failure happens at the model create step. So let's not block this change.

**Comment by grapesmoker** [comment]
Yeah, I tracked it down to a broken copy/paste in an earlier notice. I'll fix the source. Markers should never be over 25, as they're basically either of the form `(x)` or `x.` (with the `x` being at most a few characters).

**Pull request merged**
